-- FUNCTION UPDATE TIMESTAMP
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- TRIGGERS

-- UPDATE TIMESTAMP CATEGORIES
DROP TRIGGER IF EXISTS set_timestamp ON categories;
CREATE TRIGGER set_timestamp BEFORE
UPDATE ON categories FOR EACH ROW
EXECUTE FUNCTION update_timestamp ();

-- UPDATE TIMESTAMP NEWS
DROP TRIGGER IF EXISTS set_timestamp ON news;
CREATE TRIGGER set_timestamp BEFORE
UPDATE ON news FOR EACH ROW
EXECUTE FUNCTION update_timestamp ();

-- UPDATE TIMESTAMP PERMISSIONS
DROP TRIGGER IF EXISTS set_timestamp ON permissions;
CREATE TRIGGER set_timestamp BEFORE
UPDATE ON permissions FOR EACH ROW
EXECUTE FUNCTION update_timestamp ();